LIBJSON_C_DIR = json-c
LIBJSON_C_HEADERS = \
	arraylist.h \
	bits.h \
	debug.h \
	json.h \
	json_config.h \
	json_c_version.h \
	json_inttypes.h \
	json_object.h \
	json_object_iterator.h \
	json_object_private.h \
	json_tokener.h \
	json_util.h \
	linkhash.h \
	printbuf.h \
	random_seed.h


LIBJSON_C_OBJ = \
	$(LIBJSON_C_DIR)/arraylist.o \
	$(LIBJSON_C_DIR)/debug.o \
	$(LIBJSON_C_DIR)/json_c_version.o \
	$(LIBJSON_C_DIR)/json_object.o \
	$(LIBJSON_C_DIR)/json_object_iterator.o \
	$(LIBJSON_C_DIR)/json_tokener.o \
	$(LIBJSON_C_DIR)/json_util.o \
	$(LIBJSON_C_DIR)/linkhash.o \
	$(LIBJSON_C_DIR)/printbuf.o \
	$(LIBJSON_C_DIR)/random_seed.o
