#!/bin/sh
### BEGIN INIT INFO
# Provides:          rtspserver
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop RTSP server
# Description:       This script starts/stops RTSP server
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

OPTS="&"

res=0

case "$1" in
  start)
	/usr/local/sbin/h264_v4l2_rtspserver $OPTS >/dev/null
	;;
  restart|reload|force-reload)
	killall h264_v4l2_rtspserver
	/usr/local/sbin/h264_v4l2_rtspserver $OPTS >/dev/null
	;;
  stop)
	killall h264_v4l2_rtspserver
	;;
  *)
	echo "Usage:  h264_v4l2_rtspserver [start|stop]" >&2
	res=3
	;;
esac

exit $res
